name: build

on:
  push:
    branches: [develop, "feature/**"]
  pull_request:
    branches: [develop, main]

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # MSVCコンパイラ環境をパスに通す
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      # Ninjaをセットアップ
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master

      # 3. Configure (x64-release-ci プリセットを使用)
      - name: Configure
        run: cmake --preset x64-release-ci

      # 4. Editor ビルド
      - name: Build Editor
        run: cmake --build --preset editor-release-ci